-- =============================================
-- Fix: Drop overly restrictive CHECK constraint
-- on connection_requests.relationship_type
-- =============================================
-- The original CHECK only allowed: father, mother, sibling, spouse, child
-- But the app stores semantic labels like: Bua, Chacha/Tau, Father-in-law, etc.
-- This caused silent INSERT failures for extended relations.
-- =============================================

-- Drop the constraint (name is auto-generated by Supabase)
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT con.conname INTO constraint_name
  FROM pg_constraint con
  JOIN pg_attribute att ON att.attnum = ANY(con.conkey) AND att.attrelid = con.conrelid
  WHERE con.conrelid = 'public.connection_requests'::regclass
    AND att.attname = 'relationship_type'
    AND con.contype = 'c';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.connection_requests DROP CONSTRAINT %I', constraint_name);
    RAISE NOTICE 'Dropped CHECK constraint: %', constraint_name;
  ELSE
    RAISE NOTICE 'No CHECK constraint found on relationship_type — nothing to drop.';
  END IF;
END $$;
